FROM node:18
RUN mkdir /app
WORKDIR /app
# COPY package*.json ./
# RUN npm i
# COPY . .
# EXPOSE 3000
# CMD [ "npm", "start" ]
#COPY ./src /app
VOLUME /app

#docker run -it -v ./src:/app  apicontatos bash

#docker build --pull --rm -f ".docker/Dockerfile" -t apicontatos:latest ".docker" 

#docker run -v /caminho/para/seu/diretorio/src:/app/src -p 3000:3000

#docker run --user $(id -u):$(id -g) --rm -it -v ./src:/app  apicontatos:latest bash

